import type { Metadata } from "next";
import Link from "next/link";
import LeadForm from "../components/LeadForm";

export const metadata: Metadata = { title: "North · Marketing com direção para negócios locais", description: "Estratégia, conteúdo e performance conectados a uma operação clara para negócios locais premium.", alternates: { canonical: "/lp" }, openGraph: { title: "North · Marketing com direção", description: "Transforme marketing fragmentado em uma operação previsível.", type: "website" } };

const CASES = [
  { vertical: "Gastronomia & conveniência", name: "Baita", copy: "Conteúdo, mídia e rotina comercial conectados para transformar presença local em demanda.", tone: "sage" },
  { vertical: "Estética automotiva", name: "Chris Car Care", copy: "Posicionamento premium e aquisição regional com uma operação que dá visibilidade à agenda.", tone: "sand" },
  { vertical: "Serviços regionais", name: "Aurora", copy: "Estratégia e produção alinhadas à jornada real de quem pesquisa, compara e compra na região.", tone: "blue" },
];
const FAQ = [
  ["A North atende apenas esses três segmentos?", "Não. Eles orientam nossa especialização inicial, mas o diagnóstico avalia negócios locais com operação, margem e ambição compatíveis com o método."],
  ["Existe um plano pronto?", "Não começamos por um pacote. Mapeamos o momento do negócio e recomendamos o nível de parceria, as frentes e o ritmo de trabalho mais adequados."],
  ["Quanto preciso investir?", "O formulário pergunta uma faixa para que a conversa seja objetiva. O investimento final depende da estrutura, da região, das metas e do escopo recomendado."],
  ["Como acompanho o trabalho?", "Briefings, calendário, aprovações, documentos e indicadores ficam organizados no Portal North, com responsabilidades e próximos passos visíveis."],
  ["Em quanto tempo começamos?", "Depois do diagnóstico e da definição do escopo, a imersão organiza acessos, contexto e prioridades antes da primeira produção."],
];

function PortalDemo() { return <div className="portal-demo" aria-label="Demonstração ilustrativa do Portal North"><div className="demo-top"><span className="demo-logo">north</span><span>Visão da operação</span><i /></div><div className="demo-layout"><aside><b>Visão geral</b><span>Plano de ação</span><span>Produção</span><span>Aprovações</span><span>Performance</span></aside><div className="demo-main"><div className="demo-heading"><div><small>AGOSTO · CICLO 03</small><strong>A rota está clara.</strong></div><em>8 entregas ativas</em></div><div className="demo-kpis"><div><small>Prontas</small><b>12</b><i style={{width:"78%"}} /></div><div><small>Em aprovação</small><b>04</b><i style={{width:"45%"}} /></div><div><small>Próximo marco</small><b>19 ago</b><i style={{width:"62%"}} /></div></div><div className="demo-flow"><span>Briefing validado</span><i /><span>Produção em curso</span><i /><span>Resultados</span></div></div></div><span className="demo-note">DEMONSTRAÇÃO ILUSTRATIVA · DADOS NÃO REAIS</span></div>; }

export default function LandingPage() {
  return <>
    <section className="hero-v2 dark-section"><div className="site-wrap hero-grid-v2"><div className="hero-copy-v2"><p className="eyebrow light">MARKETING PARA NEGÓCIOS LOCAIS PREMIUM</p><h1>Mais que presença.<br/><em>Direção para crescer.</em></h1><p>Unimos estratégia, conteúdo e performance em uma operação clara — para sua marca atrair as pessoas certas e transformar atenção em receita.</p><div className="hero-actions"><a href="#diagnostico" className="site-btn light" data-track="cta_hero">Solicitar diagnóstico <span>↗</span></a><Link href="/como-funciona" className="text-link light">Conhecer o método →</Link></div><small className="hero-proof">Diagnóstico estratégico · conversa direta · sem proposta genérica</small></div><div className="hero-visual"><div className="orbit" aria-hidden><span /><i /><b>N</b></div><PortalDemo /></div></div></section>

    <section className="site-section problem"><div className="site-wrap split-copy"><div><p className="eyebrow">QUANDO TUDO PARECE URGENTE</p><h2>Marketing sem operação vira <em>ruído.</em></h2></div><div><p>Ideias soltas, fornecedores desconectados, aprovações no WhatsApp e métricas sem contexto drenam tempo sem construir uma direção.</p><ul className="check-list"><li>Você não sabe o que priorizar</li><li>A produção depende de cobranças</li><li>O resultado não conversa com o negócio</li></ul></div></div></section>

    <section className="site-section method dark-section"><div className="site-wrap"><div className="section-heading light"><p className="eyebrow light">MÉTODO NORTH</p><h2>Clareza para decidir.<br/><em>Ritmo para executar.</em></h2><p>Uma rota única conecta intenção, produção e aprendizado.</p></div><div className="method-grid">{[["01","Imersão","Entendemos contexto, oferta, público e capacidade comercial."],["02","Direção","Definimos posicionamento, prioridades e indicadores que importam."],["03","Operação","Produzimos, aprovamos e publicamos em ciclos visíveis no portal."],["04","Evolução","Lemos os sinais, aprendemos e recalibramos a próxima rota."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="portal-block"><div><p className="eyebrow light">PORTAL NORTH</p><h3>A estratégia não fica em uma apresentação.</h3><p>Ela vira rotina: responsáveis, aprovações, documentos e desempenho organizados em um só lugar.</p><Link href="/como-funciona" className="text-link light">Ver a operação por dentro →</Link></div><PortalDemo /></div></div></section>

    <section className="site-section cases-v2"><div className="site-wrap"><div className="section-heading"><p className="eyebrow">TRÊS CONTEXTOS, UMA DIREÇÃO</p><h2>Estratégia que respeita<br/><em>a realidade local.</em></h2><p>Exemplos estruturais de como o método se adapta a diferentes jornadas de compra.</p></div><div className="case-grid">{CASES.map((item)=><article className={`case-v2 ${item.tone}`} key={item.name}><div className="case-placeholder"><span>ESPAÇO RESERVADO PARA IMAGEM AUTORIZADA</span><i /></div><div><small>{item.vertical}</small><h3>{item.name}</h3><p>{item.copy}</p><span className="provisional">CASE ILUSTRATIVO · ATIVOS E RESULTADOS SOB APROVAÇÃO</span></div></article>)}</div></div></section>

    <section className="site-section offer-band"><div className="site-wrap"><div className="section-heading"><p className="eyebrow">UMA PARCERIA, QUATRO FRENTES</p><h2>O que precisa andar,<br/><em>anda junto.</em></h2></div><div className="offer-grid">{[["Estratégia","Posicionamento, oferta, campanha e plano de ação."],["Conteúdo","Roteiro, captação, design, edição e calendário."],["Performance","Mídia paga, leitura de dados e otimização contínua."],["Operação","Briefing, aprovações, responsabilidades e governança."]].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="center"><Link className="site-btn ghost" href="/planos">Conhecer modelos de parceria</Link></div></div></section>

    <section className="site-section social-proof"><div className="site-wrap"><p className="eyebrow">PROVAS EM VALIDAÇÃO</p><blockquote>“A North nos ajudou a enxergar marketing como operação, não como uma sequência de posts.”</blockquote><p className="provisional">DEPOIMENTO PROVISÓRIO · NOME, CARGO E EMPRESA PENDENTES DE AUTORIZAÇÃO</p></div></section>

    <section className="site-section faq-section"><div className="site-wrap faq-layout"><div><p className="eyebrow">PERGUNTAS FREQUENTES</p><h2>Antes de<br/><em>começar.</em></h2><p>Se a sua dúvida não estiver aqui, ela entra na conversa de diagnóstico.</p></div><div className="faq-list">{FAQ.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>

    <section id="diagnostico" className="site-section lead-section dark-section"><div className="site-wrap lead-layout"><div><p className="eyebrow light">PRÓXIMA DIREÇÃO</p><h2>Vamos entender<br/><em>o seu momento.</em></h2><p>Conte o essencial. A North analisa o contexto e leva a conversa para o WhatsApp já com uma direção inicial.</p><ul><li>Leva cerca de 2 minutos</li><li>Sem compromisso ou proposta automática</li><li>Seus dados ficam protegidos</li></ul></div><LeadForm /></div></section>
  </>;
}
