"use client";

import { useState } from "react";
import { getAttribution, getConsent, track } from "./analytics";

type Fields = { name:string; company:string; phone:string; segment:string; region:string; objective:string; investment:string; website:string };
const initial: Fields = { name:"", company:"", phone:"", segment:"", region:"", objective:"", investment:"", website:"" };

export default function LeadForm() {
  const [step,setStep] = useState(1); const [fields,setFields] = useState(initial); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  const update = (key:keyof Fields) => (event: React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>) => setFields((v)=>({...v,[key]:event.target.value}));
  function next(event:React.FormEvent) { event.preventDefault(); setError(""); if(!fields.name.trim()||!fields.company.trim()||fields.phone.replace(/\D/g,"").length<10){setError("Preencha nome, empresa e um WhatsApp válido.");return;} setStep(2); track("lead_step_completed",{step:1}); }
  async function submit(event:React.FormEvent){event.preventDefault();setError("");if(!fields.segment||!fields.region.trim()||!fields.objective.trim()||!fields.investment){setError("Complete os campos para enviarmos seu diagnóstico.");return;}setBusy(true);track("lead_step_completed",{step:2});try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...fields,source_page:window.location.pathname,consent_analytics:getConsent()==="accepted",utm:getAttribution()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível enviar agora.");track("lead_submit_success",{source_page:window.location.pathname});track("whatsapp_redirect",{lead_id:data.id});window.location.assign(data.whatsapp_url);}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar agora.");track("lead_submit_error",{source_page:window.location.pathname});setBusy(false);}}
  return <form className="lead-form" onSubmit={step===1?next:submit} onFocus={()=>track("lead_form_started",{source_page:location.pathname})}><div className="form-progress"><span>ETAPA {step} DE 2</span><div><i className="on"/><i className={step===2?"on":""}/></div></div>{step===1?<fieldset><legend>Primeiro, sobre você</legend><label>Seu nome<input value={fields.name} onChange={update("name")} autoComplete="name" required placeholder="Como podemos chamar você?"/></label><label>Empresa<input value={fields.company} onChange={update("company")} autoComplete="organization" required placeholder="Nome do seu negócio"/></label><label>WhatsApp<input value={fields.phone} onChange={update("phone")} inputMode="tel" autoComplete="tel" required placeholder="(00) 00000-0000"/></label><label className="honeypot" aria-hidden>Website<input value={fields.website} onChange={update("website")} tabIndex={-1} autoComplete="off"/></label></fieldset>:<fieldset><legend>Agora, sobre o negócio</legend><label>Segmento<select value={fields.segment} onChange={update("segment")} required><option value="">Selecione</option><option>Estética automotiva</option><option>Gastronomia</option><option>Serviços regionais</option><option>Outro negócio local</option></select></label><label>Cidade ou região<input value={fields.region} onChange={update("region")} required placeholder="Ex.: Campinas e região"/></label><label>Principal objetivo<textarea value={fields.objective} onChange={update("objective")} required placeholder="O que precisa mudar nos próximos meses?" rows={3}/></label><label>Faixa de investimento mensal<select value={fields.investment} onChange={update("investment")} required><option value="">Selecione</option><option value="até-3k">Até R$ 3 mil</option><option value="3k-6k">R$ 3 mil a R$ 6 mil</option><option value="6k-12k">R$ 6 mil a R$ 12 mil</option><option value="12k+">Acima de R$ 12 mil</option></select></label></fieldset>}<div className="form-actions">{step===2&&<button type="button" className="back-btn" onClick={()=>setStep(1)}>← Voltar</button>}<button className="site-btn solid" type="submit" disabled={busy}>{step===1?"Continuar →":busy?"Enviando…":"Enviar e abrir WhatsApp →"}</button></div>{error&&<p className="form-error" role="alert">{error}</p>}<p className="form-privacy">Ao enviar, você concorda com nossa <a href="/politica-de-privacidade">Política de Privacidade</a>. Seus dados de contato não são enviados ao analytics.</p></form>;
}
